### ISSUE TITLE
host intro slides (from the ipython notebook) somewhere for public viewing

### ISSUE THREAD

**Issue by robertmuil** [zalando/expan#10]
Currently, the ipython notebook (`Expan-Intro.ipynb`) is available locally as slides with the `serve_intro_slides` script.

It would be great to host the converted notebook on a public server somewhere so that prospective users can view it without cloning or running a local jupyter server.

**Comment by elezar** [comment]
Just as a note. GitHub supports the viewing of Ipython Notebooks on the server. I think this requires that the notebook be committed with with all the cells run, but this should give users an idea of the expected output.

**Comment by robertmuil** [comment]
So it does! Thanks Evan, appreciated.
Would still be nice to have properly hosted to support the slide functionality, but that's a minor thing.

**Comment by jbao** [comment]
so there seems to be some tutorial about hosting reveal.js slides on gh-pages http://stackoverflow.com/questions/31163633/how-to-host-a-reveal-js-presentation

**Comment by lasomethingsomething** [comment]
Hey @jbao @elezar: can we close this issue? It dates back to May 2016.

**Comment by jbao** [comment]
Low priority, close for now.
