### ISSUE TITLE
What's the point of *_delta() methods accepting an (empty) Result instance?

### ISSUE THREAD

**Issue by gbordyugov** [zalando/expan#100]
In the current implementation, all `*_delta()` methods accept a `res` argument, being (oftentimes) an empty instance of the `Result` class. This instance is then updated with the results of the analysis.

On the other hand, other analysis methods, such as `feature_check()`, `sga()`, and `trend()` create a `Result` instance on the fly, populate it with results and return it.

What is the motivation between those two different approaches?

**Comment by shansfolder** [comment]
Looks ok after discussion.
