### ISSUE TITLE
"variant_subset" parameter of Experiment.fixed_horizon_delta() is not used

### ISSUE THREAD

**Issue by gbordyugov** [zalando/expan#103]
My understanding is that the code

https://github.com/zalando/expan/blob/dev/expan/core/experiment.py#L456-L460

is not relevant for the call of `delta_all_variants()` at

https://github.com/zalando/expan/blob/dev/expan/core/experiment.py#L475

**Comment by jbao** [comment]
That's true, yet another unused parameter:-P

**Comment by gbordyugov** [comment]
will be fixed by https://github.com/zalando/expan/pull/104
