### ISSUE TITLE
Question about percentiles in Bayesian early stopping

### ISSUE THREAD

**Issue by shansfolder** [zalando/expan#109]
As I understood from code, percentiles values for regular delta and group sequential delta are using t statistics.
 e.g. in the result object, "pctile" could be (2.5, 50, 97.5), "value" can be the corresponding t statistics (0.1, 0.8, 0.1).
 
On the other hand, percentiles values for two Bayesian delta are using a fixed 0.95 credible interval.
In the result object, "pctile" is always ("lower", "upper"), "value" is the corresponding index of posterior distribution.

I think they are two completely different concept, and if I understood correctly, should we put them into different columns in the result object?

**Comment by shansfolder** [comment]
ok, on second thought, they have something in common in higher abstraction. ;)
 
One can find the "value" of the random variable being tested, given a defined metric "pctile"
* in frequentist approaches **pctile** is the percentile of the test distribution
* whereas in Bayesian approaches **pctile** is the lower/upper bound of a 0.95 credible interval of the test distribution.

**Comment by mkolarek** [comment]
exactly, sorry haven't had time to look at this sooner. @gbordyugov has worked on a new concept for the Results structure so these issues will be taken into account, but for now I would not mess with it much... for testing the early stopping methods I believe the current implementation should suffice.

**Comment by shansfolder** [comment]
closed since the structure of result object is under planed
