### ISSUE TITLE
Make baseline_variant mandatory in the metadata?

### ISSUE THREAD

**Issue by jbao** [zalando/expan#12]
By doing so, we can deprecate the baseline_variant argument in the Experiment constructor, so to create an Experiment object, one only needs the kpi_df, feature_df and metadata, which is more intuitive.

**Comment by robertmuil** [comment]
Hmm, I'm not sure about that... `baseline_variant` is more than just another metadata attribute - it really defines the difference between `ExperimentData` and `Experiment`.
If we take it out as an explicit argument, we still have to enforce that it is defined in the metadata, which feels quite similar in terms of usage but just less transparent to the user.
