### ISSUE TITLE
No module named experiment and test_data

### ISSUE THREAD

**Issue by pangeran-bottor** [zalando/expan#13]
from expan.experiment import Experiment raises an ImportError: No module named experiment.
I have to change it to from expan.core.experiment import Experiment and it works.

Also from tests.test_data import generate_random_data doesn't work, I have to use 
from tests.tests_data import generate_random_data but this raises an another error cannot import name generate_random_data.

**Comment by jbao** [comment]
right, we need to investigate the first behavior further, but at least for the moment the second issue can be solved by

`from tests.tests_core.test_data import generate_random_data`

I agree that the folder names might not be very intuitive, but I'm open to suggestions;-)
