### ISSUE TITLE
Implement __version__

### ISSUE THREAD

**Issue by jbao** [zalando/expan#14]
to enable the standard call expan.**version**

**Comment by pangeran-bottor** [comment]
I create PR for this : https://github.com/zalando/expan/pull/15

**Comment by robertmuil** [comment]
Do you mean the standard call `expan.__version__`?

Currently can do `expan.version()` to get the version string (it's a function...)

**Comment by robertmuil** [comment]
PR #19 from Pangeran merged in `dev`. If everyone's ok with it, I'll merge it into `master`. This issue will then be closed.

**Comment by jbao** [comment]
yes, +1 to @pangeran-bottor, I'm fine with the PR.
