### ISSUE TITLE
Update to ExpAn-Intro.ipynb

### ISSUE THREAD

**Issue by louisryan** [zalando/expan#141]
Since recent updates, the material in ExpAn-Intro.ipynb is out of date and cannot be run. The tool is fantastic, but the barrier to entry is unnecessarily high at the moment.

**Comment by gbordyugov** [comment]
Thanks a lot for opening the issue, we've indeed changed a lot recently and the documentation has to catch up - we're working on this.

**Comment by shansfolder** [comment]
@louisryan documentations are updated now. Please check out the latest ```dev``` or ```master``` branch. Or use the latest release v0.6.1. Let us know if it works. Thank you.

**Comment by louisryan** [comment]
🚀
