### ISSUE TITLE
Result statistics in Baeysian methods

### ISSUE THREAD

**Issue by shansfolder** [zalando/expan#142]
In the [Stan model](https://github.com/zalando/expan/blob/dev/expan/models/normal_kpi.stan) the difference of mean is modeled by ```alpha```, while in [early_stopping.py](https://github.com/zalando/expan/blob/dev/expan/core/early_stopping.py#L274-L283) we return the trace of ```delta``` in the result.

**Comment by jbao** [comment]
As far as I know, `delta` is a normalized version of `alpha`, which is unit-less and makes it easy to set the threshold for the Bayes factor.

**Comment by gbordyugov** [comment]
@jbao as far as I can see from

https://github.com/zalando/expan/blob/dev/expan/core/statistics.py#L89
https://github.com/zalando/expan/blob/dev/expan/core/statistics.py#L7

`delta` is just the difference of means (we've never touched that code).

**Comment by jbao** [comment]
@gbordyugov sorry, I was actually referring to https://github.com/zalando/expan/blob/dev/expan/models/normal_kpi.stan#L16, so `alpha` is the absolute difference between two means, but we return the posterior samples of `delta` because it's easy for the Bayes factor calculation etc.

**Comment by gbordyugov** [comment]
@jbao yes, exactly, I was more familiar with how `delta` is computed in early stopping methods, that's why the slightly different definition of it in regular statistics surprised me.

**Comment by gbordyugov** [comment]
@shansfolder you and me were apparently talking about two different issues when discussing this today ;)

**Comment by jbao** [comment]
@gbordyugov you're right, the notation was confusing...

**Comment by shansfolder** [comment]
Thank you both for clearing this issue. I've just addressed it in pull request #144.

**Comment by shansfolder** [comment]
fixed by #144
