### ISSUE TITLE
Applying bins to data frames

### ISSUE THREAD

**Issue by gbordyugov** [zalando/expan#165]
If `apply()` were replaced by `__call__()` in
https://github.com/zalando/expan/blob/dev/expan/core/binning.py#L48

it would be easier to apply bins to data frames by simply writing `binned_df = bin(df, feature)`

**Comment by gbordyugov** [comment]
addressed by https://github.com/zalando/expan/pull/169

**Comment by daryadedik** [comment]
@gbordyugov can I close this issue?
