### ISSUE TITLE
Sample size with an unequal split ratio

### ISSUE THREAD

**Issue by jbao** [zalando/expan#187]
Hi all,

I'm wondering in the sample size formula,

https://github.com/zalando/expan/blob/master/expan/core/statistics.py#L168

whether the number of variants `n` should be replaced by `1+r`? Esp. considering the current formula will give a smaller sample size with an increasing split ratio `r`, ie. an unequal split would require a smaller sample size to reach the same error rate, which is not so intuitive?

Thanks!

**Comment by gbordyugov** [comment]
Please discuss and review

https://github.com/zalando/expan/pull/188
