### ISSUE TITLE
Add P(uplift>0) as a statistic

### ISSUE THREAD

**Issue by jbao** [zalando/expan#2]
This probability will be calculated from the existing result data, based on the percentiles and the normal assumption.

**Comment by robertmuil** [comment]
I am still in favour of implementing this using the result structure as it was originally intended: with percentiles in one column and value in another, using the 'uplift_pctile' statistic. However, this can be changed later if required.

Bringing over discussion from GHE:

Robert:

> two possible implementations of this:
> 1. as a completely new statistic called e.g. 'prob_greater_0', which would then also need something like 'prob_greater_cost'... and only the 'value' column would be relevant, 'pctile' would be nan.
> 2. as a pctile, with value=0 or value=. simpler, fits existing structure, and wouldn't be difficult to retrieve (res.statistic('pctile').query('value=0')

Till:

> Do not like solution 2 as it sounds very hacked (and requires previous knowledge). The query for solution 1 should also not be too difficult, as it has a name (so same as retrieving mean)

Robert:

> I don't think solution 2 is hacked: it fits exactly what the question is, namely 'what is the pctile at which 0 or cost occurs'. Putting this in as a statistic seems to me more hacked because it throws away the pctile column, and requires the statistic column to include something numeric (0 or cost) in the string.

How are we going to represent several different costs?
What if the costs arise after the calculation?
Solution 2 allows at least approx. answers to these at a later time.

**Comment by jbao** [comment]
also just thought about that again, 
- encoding the probability as a percentile makes the results structure generic, but it has at least two drawbacks
  - the probabilities for different variants are persisted in the same column, which can only be reference by the variant name and a '0', not entirely impossible, but feels counter-intuitive
  - additional arithmetic operation required, since the value we store in the result is actually 1 - probability
- yes, we need to make the treatment cost as a parameter, rather than a hard-coded 0

**Comment by robertmuil** [comment]
Hi Jie,
regarding the points you mentioned:
1. same column: I don't understand: each variant is a separate column...
2. additional arithmetic: yes, but this can easily be implemented in a property to expose it as though it were a statistic.
3. treatment cost: my point was rather more conceptual: what if there are several different possible treatment costs? they will all be in the result dataframe as separate statistics. this will be ugly even with a single treatment cost.
4. In addition, the treatment costs (and 0) will be encoded in a string. Which feels to me hacky.
