### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by tsterbak** [zalando/expan#21]
Will there be a version for python3?

**Comment by robertmuil** [comment]
Good point - short answer is yes!

Longer is: we've not got experience with it... so if you'd like to submit a PR, we'd be stoked!

**Comment by ghost** [comment]
Is any updates of Python 3 version?
Thank you.

**Comment by jbao** [comment]
Hi, Python 3 support is on our roadmap, esp. since the next major IPython release will require Python 3, so it's probably high time to get this work started;-)

**Comment by jbao** [comment]
btw, just quickly came up with a first version that supports both python 2 and 3 [here](https://github.com/zalando/expan/tree/feature/2to3), still need to tweak some config files to add python 3 into the CI pipeline.

**Comment by jbao** [comment]
This is resolved by #43 .
