### ISSUE TITLE
Numbers cannot appear in variable names for derived metrics

### ISSUE THREAD

**Issue by jbao** [zalando/expan#58]
Currently the regex does not match numbers when constructing derived metrics from the formula.

**Comment by gbordyugov** [comment]
Hi, 

could you please point to the potential location of the fix (file/linenumber)?

**Comment by jbao** [comment]
The regex is at https://github.com/zalando/expan/blob/dev/expan/core/experiment.py#L416, this fix probably needs a concept, since numbers are in general allowed in formulas of derived metrics.

**Comment by gbordyugov** [comment]
would `([a-zA-Z][0-9a-zA-Z_]*)` be the relevant solution? Basically saying 'an alphanumerical identifier starting with an alpha?'

**Comment by jbao** [comment]
@gbordyugov good idea, we can implement it this way and document properly.

**Comment by gbordyugov** [comment]
https://github.com/zalando/expan/pull/70 - please comment
