### ISSUE TITLE
Rethink Results structure

### ISSUE THREAD

**Issue by mkolarek** [zalando/expan#66]
The goal of the current implementation of the Results structure is to enable the user to easily concatenate the results of multiple analyses (say delta() + sga()).
This functionality hasn't been used much, so it would be a good idea to rethink the Results structure and maybe aim to simplify it.

**Comment by gbordyugov** [comment]
I see as one of potential improvements the possibility of eliminating the intermediate data frame objects (produced by `*_to_dataframe_*()` functions)

**Comment by gbordyugov** [comment]
duplicate of https://github.com/zalando/expan/issues/82
