### ISSUE TITLE
allow constructing an Experiment from an ExperimentData

### ISSUE THREAD

**Issue by robertmuil** [zalando/expan#8]
Currently, although it's a subclass, no way to construct an `Experiment` from an `ExperimentData` which is a bit counter-intuitive.

Not really necessary (can always just pass whatever you passed to the `ExperimentData` constructor directly to the `Experiment`, but we should allow this.

Low priority.

**Comment by jbao** [comment]
this relates to #12, I think for the moment we'll keep separating the Experiment and ExperimentData classes.

**Comment by robertmuil** [comment]
Yes, they should be kept as separate classes, but I just thought it would be nice to be able to _construct_ an `Experiment` from an `ExperimentData`.

**Comment by jbao** [comment]
Low priority, close for now.
