### ISSUE TITLE
Experiment.sga() assumes features and KPIs are merged in self.metrics

### ISSUE THREAD

**Issue by jbao** [zalando/expan#87]
This will break if one constructs the `ExperimentData` object with two separate feature and KPI data frames, in which case we need to merge them manually.

**Comment by gbordyugov** [comment]
did you actually find the place in code where `self.metrics` are created?

**Comment by jbao** [comment]
Turns out `self.metrics` is a property and already created

https://github.com/zalando/expan/blob/dev/expan/core/experimentdata.py#L197

Thus this is not a bug at all and will close now.
