### ISSUE TITLE
reenable means and bounds functions on Results object

### ISSUE THREAD

**Issue by robertmuil** [zalando/expan#9]
Were temporarily removed after a change of structure... need to reenable them.
Especially because the `Results.__str__` function relies on them.

**Comment by robertmuil** [comment]
This is a bit of a problem because it is causing our ipython notebook introduction to have a bunch of errors. Shouldn't be a hard fix...

**Comment by lasomethingsomething** [comment]
Hey @jbao @elezar: can we close this issue? It dates back to May 2016.

**Comment by jbao** [comment]
This also relates to the rewriting of the `Results.statistic()` function.

**Comment by gbordyugov** [comment]
not applicable after https://github.com/zalando/expan/pull/134
